### ISSUE TITLE
Incorrect sender id

### ISSUE THREAD

**Issue by kellslte** [djunehor/laravel-sms#6]
When using the SmartSmsSolutions class to send text messages, I noticed that the sender id I set to be used isn't used. It usually delivers the message with another sender id different from what I have specified. Could this be a result of the way the API token was created?

**Comment by djunehor** [comment]
Sometimes, SMS providers changed the senderId if it's breaking one of their rules e.g blacklisted keyword. Have you tried any other senderId and the result is the same?

**Comment by kellslte** [comment]
I am currently speaking with one of their customer care agents. Hopefully we can resolve the matter from their end

**Comment by djunehor** [comment]
Sounds good

**Comment by kellslte** [comment]
The customer care representative said that I should submit the sender Id for whitelisting. I guess that solves this issue
